name: Generate calendar
on:
  push:
    branches: [ master ]
jobs:
  calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          git clone https://github.com/rkdarst/yaml-to-ical
      - name: Install dependencies
        run: |
          python -m pip install -r yaml-to-ical/requirements.txt
      - name: build
        run: |
          make build
          mkdir www/
          cp *.ics www/
          echo '<a href="AaltoSciComp-events.ics">link</a>' > www/index.html
          date >> www/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www
